import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { getLoginHistory } from '../api/login-history-api';

export function LoginHistoryPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [successful, setSuccessful] = useState('');
  const history = useQuery({ queryKey: ['login-history', page, search, successful], queryFn: () => getLoginHistory(page, search, successful) });
  const updateSearch = (value: string) => { setSearch(value); setPage(1); };
  return <section className="card"><div className="card-header"><div className="row g-2"><div className="col-md-6"><div className="input-group input-group-sm"><input className="form-control" value={search} onChange={(event) => updateSearch(event.target.value)} placeholder="Search email, IP, or browser" /><span className="input-group-text"><i className="bi bi-search" /></span></div></div><div className="col-md-3"><select className="form-select form-select-sm" value={successful} onChange={(event) => { setSuccessful(event.target.value); setPage(1); }}><option value="">All results</option><option value="true">Successful</option><option value="false">Failed</option></select></div></div></div><div className="card-body table-responsive p-0">{history.isPending && <div className="p-3 text-body-secondary">Loading login history…</div>}{history.isError && <div className="alert alert-danger m-3 mb-0">{history.error.message}</div>}{history.data && <table className="table table-hover align-middle mb-0"><thead><tr><th>Time</th><th>Email</th><th>IP address</th><th>Browser / device</th><th>Result</th></tr></thead><tbody>{history.data.items.map((event) => <tr key={event.id}><td>{new Date(event.createdAt).toLocaleString()}</td><td>{event.email}</td><td>{event.ipAddress ?? '—'}</td><td className="text-truncate" style={{ maxWidth: 280 }}>{event.userAgent ?? '—'}</td><td><span className={`badge text-bg-${event.successful ? 'success' : 'danger'}`}>{event.successful ? 'Successful' : 'Failed'}</span></td></tr>)}</tbody></table>}</div>{history.data && <div className="card-footer d-flex flex-wrap justify-content-between align-items-center gap-2"><span className="text-body-secondary small">{history.data.total} event(s)</span><nav aria-label="Login history pagination"><ul className="pagination pagination-sm mb-0"><li className={`page-item ${page <= 1 ? 'disabled' : ''}`}><button className="page-link" onClick={() => setPage(page - 1)}>Previous</button></li><li className="page-item disabled"><span className="page-link">Page {page} of {history.data.totalPages}</span></li><li className={`page-item ${page >= history.data.totalPages ? 'disabled' : ''}`}><button className="page-link" onClick={() => setPage(page + 1)}>Next</button></li></ul></nav></div>}</section>;
}
