import { useQuery } from '@tanstack/react-query';
import type { HealthResponse } from '@cias/shared-types';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../../lib/api-client';

async function getHealth(): Promise<HealthResponse> {
  return apiRequest<HealthResponse>('/health');
}

export function DashboardPage() {
  const health = useQuery({ queryKey: ['health'], queryFn: getHealth, retry: false });

  return <><div className="row"><div className="col-lg-3 col-6"><div className="small-box text-bg-primary"><div className="inner"><h3>Users</h3><p>User management</p></div><i className="small-box-icon bi bi-people-fill" /><Link className="small-box-footer" to="/users">Manage users <i className="bi bi-arrow-right-circle" /></Link></div></div><div className="col-lg-3 col-6"><div className="small-box text-bg-success"><div className="inner"><h3>Roles</h3><p>Access control</p></div><i className="small-box-icon bi bi-shield-check" /><Link className="small-box-footer" to="/roles">Manage roles <i className="bi bi-arrow-right-circle" /></Link></div></div><div className="col-lg-3 col-6"><div className="small-box text-bg-warning"><div className="inner"><h3>Audit</h3><p>Login activity</p></div><i className="small-box-icon bi bi-clock-history" /><Link className="small-box-footer" to="/login-history">View history <i className="bi bi-arrow-right-circle" /></Link></div></div><div className="col-lg-3 col-6"><div className="small-box text-bg-info"><div className="inner"><h3>{health.data?.database === 'configured' ? 'Online' : 'Offline'}</h3><p>Database status</p></div><i className="small-box-icon bi bi-database-check" /><span className="small-box-footer">{health.isPending ? 'Checking API…' : health.isError ? 'API unavailable' : `Database: ${health.data?.database}`}</span></div></div></div><div className="row"><div className="col-lg-7"><div className="card"><div className="card-header"><h3 className="card-title"><i className="bi bi-lightning-charge-fill me-2" />Quick start</h3></div><div className="card-body"><p className="mb-3">Use the menu to manage users and role permissions, inspect sign-in activity, or update your password.</p><div className="d-flex flex-wrap gap-2"><Link className="btn btn-primary" to="/users"><i className="bi bi-person-plus-fill me-1" /> Add user</Link><Link className="btn btn-outline-secondary" to="/roles">Configure roles</Link></div></div></div></div><div className="col-lg-5"><div className="card card-outline card-primary"><div className="card-header"><h3 className="card-title">System status</h3></div><div className="card-body"><div className="d-flex justify-content-between border-bottom pb-2 mb-2"><span>API</span><strong className={health.isError ? 'text-danger' : 'text-success'}>{health.isError ? 'Unavailable' : 'Connected'}</strong></div><div className="d-flex justify-content-between"><span>Database</span><strong>{health.data?.database ?? 'Checking'}</strong></div></div></div></div></div></>;
}
